version: "2.3"

services:
    wordpress:
        build:
            context: ./docker/wp
            target: base
        volumes:
            - ./cwv-perf-optimize:/cwv-perf-optimize
            - ./public:/var/www/html
            - ./vendor:/vendor
        depends_on:
            - db
        extra_hosts:
            host.docker.internal: 172.17.0.1
        environment:
            XDEBUG_MODE: "off"

    wp:
        build:
            context: ./docker/wp
            target: base
        volumes:
            - ./cwv-perf-optimize:/cwv-perf-optimize
            - ./public:/var/www/html
            - ./vendor:/vendor
        depends_on:
            - db
        extra_hosts:
            host.docker.internal: 172.17.0.1
        entrypoint: ["/vendor/bin/wp"]
        user: www-data
        environment:
            XDEBUG_MODE: "off"

    server:
        build:
            context: ./docker/nginx
        links:
            - varnish
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./public:/var/www/html:ro
            - ./docker/nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/nginx/etc/ssl:/etc/nginx/ssl:ro
            - ./docker/nginx/etc/conf.d/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro

    upstream:
        build:
            context: ./docker/nginx
        links:
            - wordpress
        ports:
            - 8080:8080
            - 44380:44380
        volumes:
            - ./public:/var/www/html:ro
            - ./docker/nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/nginx/etc/ssl:/etc/nginx/ssl:ro
            - ./docker/nginx/etc/conf.d/upstream.conf:/etc/nginx/conf.d/upstream.conf:ro

    db:
        image: mariadb
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: db
            MYSQL_ROOT_PASSWORD: db

    varnish:
        image: varnish
        links:
            - upstream
        volumes:
            - ./docker/varnish/etc/default.vcl:/etc/varnish/default.vcl:ro

    plugin-tests:
        build:
            context: ./docker/wp
            target: tests
        volumes:
            - ./cwv-perf-optimize:/cwv-perf-optimize
            - ./vendor:/vendor
        working_dir: /cwv-perf-optimize
        command: ["/vendor/bin/phpunit"]
        depends_on:
            - db
        environment:
            XDEBUG_MODE: "off"

    plugin-cs:
        build:
            context: ./docker/wp
            target: base
        volumes:
            - ./cwv-perf-optimize:/cwv-perf-optimize
            - ./vendor:/vendor
        working_dir: /cwv-perf-optimize
        command: ["/vendor/bin/phpcs", "-s"]

    composer:
        image: composer
        volumes:
            - .:/app
            # Map local user Composer directory with container for cache packages
            - ~/.docker_cache/composer:/tmp/cache
        working_dir: /app

volumes:
    db_data:
