version: "2.3"

services:
    penthouse:
        build: .
        depends_on:
            - static-server
        volumes:
            - .:/penthouse-poc

    penthouse-service:
        build: .
        depends_on:
            - static-server
        volumes:
            - .:/penthouse-poc
        command: [ 'nodemon', 'server.js' ]
        ports:
            - 8080:8080

    static-server:
        build: ../docker/nginx
        volumes:
            - .:/var/www/html:ro
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
